theme: jekyll-theme-slate
title: 3rd International Workshop on Conceptual Modeling Meets Artificial Intelligence (CMAI 2021)
description: Co-Located with the 40th International Conference on Conceptual Modeling (ER 2021), 18-21 October 2021 St. Johns, Canada

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
